[app]
log_file = app.log
log_level = INFO
startup_retry_delay = 300
contract_retry_delay = 600

[settings]
# --- STRATEGY SWITCHES ---
# Trade management
allow_simultaneous_trades = true

instrument_to_trade = NIFTY
data_provider = upstox
start_time = 09:15:00
end_time = 15:25:00
record_data = false
backtest_enabled = true
backtest_csv_path = market_data_NIFTY_2026-01-20.csv
backtest_date = 2026-02-25
trading_mode = live
active_broker = Zerodha_Client_Live_1

strikes_to_monitor = 1
strike_selection_hysteresis = 5.0


[database]
host = 127.0.0.1
port = 5432
user = postgres
password = postgres
database = trading_bot
# If true, bot will fail to start without a DB connection.
required = false

[redis]
enabled = false
host = localhost
port = 6379
db = 0
# price_feed_mode options: direct (bot connects to Upstox) or shared (bot connects to Redis feed server)
price_feed_mode = direct

[brokers]
enabled_brokers = Zerodha, PaperTrade

[data_providers]
provider_list = upstox

[NIFTY]
instrument_symbol = NSE_INDEX|Nifty 50
futures_instrument_key = NSE_FO|51714
strike_interval = 50
lot_size = 65
instrument_name = NIFTY

[SENSEX]
instrument_symbol = BSE_INDEX|SENSEX
futures_instrument_key = BSE_FO|1165486
instrument_name = SENSEX
strike_interval = 100
lot_size = 20

[BANKNIFTY]
instrument_symbol = NSE_INDEX|Nifty Bank
futures_instrument_key = NSE_FO|59175
instrument_name = BANKNIFTY
strike_interval = 100
lot_size = 35

[MIDCAP]
instrument_symbol = NSE_INDEX|NIFTY MID SELECT
futures_instrument_key = NSE_FO|59181
instrument_name = MIDCAP
strike_interval = 25
lot_size = 140

[FINNIFTY]
instrument_symbol = NSE_INDEX|Nifty Fin Service
futures_instrument_key = NSE_FO|59176
strike_interval = 100
instrument_name = FINNIFTY
lot_size = 40

[PaperTrade]
client = PaperTrade
paper_trade = true
mode = paper
credentials = upstox_trading

[Zerodha]
client = Zerodha
client_list = Zerodha_Client_Live_1, Zerodha_Client_Live_2, Zerodha_Client_Paper_1
mode = multi_client
credentials = Zerodha_Client_Live_1

[Zerodha_Client_Live_1]
client = Zerodha
mode = live
credentials = Zerodha_Client_Live_1
quantity = 10
instruments_to_trade = NIFTY

[Zerodha_Client_Live_2]
client = Zerodha
mode = live
credentials = Zerodha_Client_Live_2
quantity = 1
instruments_to_trade = NIFTY

[Zerodha_Client_Paper_1]
client = Zerodha
mode = paper
credentials = Zerodha_Client_Live_1
quantity = 1
instruments_to_trade = NIFTY

[Dhan_1]
client = Dhan
mode = live
credentials = Dhan_1
quantity = 1
instruments_to_trade = NIFTY

[AngelOne_1]
client = AngelOne
mode = live
credentials = AngelOne_1
quantity = 1
instruments_to_trade = NIFTY
